### ISSUE TITLE
Running simulations fails with `NotImplementedError: Non-constant spacing not implemented`

### ISSUE THREAD

**Issue by theo-brown** [google-deepmind/torax#333]
I currently can't run any simulations, as I get the following error:
```
NotImplementedError: Non-constant spacing not implemented
```
Commit: 6aeb3223223fecce9af1d0d8dcd90a4ac624851a

To replicate: 
```
python run_simulation_main.py --config torax.examples.basic_config
```

Traceback:
```
Traceback (most recent call last):
  File ".../torax/run_simulation_main.py", line 631, in <module>
    app.run(main)
  File ".../python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File ".../python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File ".../torax/torax/run_simulation_main.py", line 464, in main
    config_loader.build_sim_and_runtime_params_from_config_module(
  File ".../torax/torax/config/config_loader.py", line 51, in build_sim_and_runtime_params_from_config_module
    sim = build_sim.build_sim_from_config(config)
  File ".../torax/torax/config/build_sim.py", line 219, in build_sim_from_config
    return sim_lib.build_sim_object(
  File ".../torax/torax/sim.py", line 910, in build_sim_object
    initial_state = get_initial_state(
  File ".../torax/torax/sim.py", line 676, in get_initial_state
    initial_core_profiles = core_profile_setters.initial_core_profiles(
  File .../torax/torax/core_profile_setters.py", line 746, in initial_core_profiles
    value=source_models_lib.calc_psidot(
  File ".../torax/torax/sources/source_models.py", line 562, in calc_psidot
    ddrnorm_sigma_rnorm2_over_f2 = jnp.gradient(
  File ".../python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 1154, in gradient
    raise NotImplementedError("Non-constant spacing not implemented")

**Comment by theo-brown** [comment]
Sorry, should've read the announcement (https://github.com/google-deepmind/torax/discussions/293). Fix is to update JAX to 0.4.31.
