### ISSUE TITLE
`KeyError` when running example configs

### ISSUE THREAD

**Issue by theo-brown** [google-deepmind/torax#570]
### Problem
I'm not able to run any of the examples in `torax.examples` from the current commit (https://github.com/google-deepmind/torax/commit/2b470108d850d19aea676fdef94c4d449c0f85d1).

### To replicate

Newly cloned repo, Python 3.12, installed with `pip install -e .[dev]`.

Running `python run_simulation_main.py --config=torax.examples.basic_config` raises the following error

```
I1126 18:38:05.371396 23356775410688 plasma_composition.py:78] 
          Config input Zeff not directly defined at rhonorm=1.0.
          Zeff_face at rhonorm=1.0 set from constant values or constant extrapolation.
          
Traceback (most recent call last):
  File "/.../torax/run_simulation_main.py", line 660, in <module>
    app.run(main)
  File "/.../python3.12/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/.../python3.12/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/.../torax/run_simulation_main.py", line 488, in main
    config_loader.build_sim_and_runtime_params_from_config_module(
  File "/.../torax/torax/config/config_loader.py", line 51, in build_sim_and_runtime_params_from_config_module
    sim = build_sim.build_sim_from_config(config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../torax/config/build_sim.py", line 257, in build_sim_from_config
    'set_pedestal' in config['runtime_params']['profile_conditions']
                      ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'profile_conditions'
```

Running `python run_simulation_main.py --config=torax.examples.iterhybrid_rampup` or `python run_simulation_main.py --config=torax.examples.iterhybrid_predictor_corrector` raises:

```
Traceback (most recent call last):
  File "/.../torax/run_simulation_main.py", line 660, in <module>
    app.run(main)
  File ".../python3.12/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/.../python3.12/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/.../torax/run_simulation_main.py", line 488, in main
    config_loader.build_sim_and_runtime_params_from_config_module(
  File "/.../torax/torax/config/config_loader.py", line 48, in build_sim_and_runtime_params_from_config_module
    new_runtime_params = build_sim.build_runtime_params_from_config(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../tab53/torax/torax/config/build_sim.py", line 312, in build_runtime_params_from_config
    return config_args.recursive_replace(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../torax/torax/config/config_args.py", line 389, in recursive_replace
    flattened_changes[key] = recursive_replace(
                             ^^^^^^^^^^^^^^^^^^
  File "/.../tab53/torax/torax/config/config_args.py", line 428, in recursive_replace
    issubclass(keys_to_types[key], enum.Enum)
               ~~~~~~~~~~~~~^^^^^
KeyError: 'Tiped'
```

**Comment by theo-brown** [comment]
@Nush395 I believe this bug was introduced in 1f8669eccf846e7cc5d9a6837daafd195812278a, as I'm able to run these commands on e506f63 with no issue.

**Comment by Nush395** [comment]
Hey @theo-brown, thanks for raising the issue and identifying the offending commit. You're indeed right that the example configs were broken by one of my recent changes. @jcitrin is putting out a fix.

Sorry for the trouble!

**Comment by theo-brown** [comment]
No trouble at all! Exciting to see the development that's gone on. No pressure to fix urgently, I can work from e506f63 and then fast-forward later.

**Comment by theo-brown** [comment]
It might be worth adding a unit test to check that the example configs all run? I can do that if it would be helpful.

**Comment by Nush395** [comment]
> It might be worth adding a unit test to check that the example configs all run? I can do that if it would be helpful.

Yes, great idea. We will be doing that :)

**Comment by jcitrin** [comment]
#571  . Thanks for raising!

**Comment by theo-brown** [comment]
Thanks for fixing!
